[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "renovate-test"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "click==8.0.*",
  "django>=4.1.0",
]

[project.optional-dependencies]
test = [
  "pytest==9.0.*",
]

[dependency-groups]
dev = [
  "tox",
]
