[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "renovate-test"
version = "0.1.0"
dependencies = [
  "click",
  "django==4.0",
]

[project.optional-dependencies]
test = [
  "pytest",
]

[dependency-groups]
dev = [
  "tox",
]
